/* tslint:disable */
/* eslint-disable */
/**
 * Extension Config API
 * API to submit and publish an ExtensionConfig object
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateExtension201Response
 */
export interface CreateExtension201Response {
    /**
     * 
     * @type {boolean}
     * @memberof CreateExtension201Response
     */
    success?: boolean;
    /**
     * The ID of the created extension
     * @type {string}
     * @memberof CreateExtension201Response
     */
    id?: string;
}

/**
 * Check if a given object implements the CreateExtension201Response interface.
 */
export function instanceOfCreateExtension201Response(value: object): value is CreateExtension201Response {
    return true;
}

export function CreateExtension201ResponseFromJSON(json: any): CreateExtension201Response {
    return CreateExtension201ResponseFromJSONTyped(json, false);
}

export function CreateExtension201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateExtension201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function CreateExtension201ResponseToJSON(json: any): CreateExtension201Response {
    return CreateExtension201ResponseToJSONTyped(json, false);
}

export function CreateExtension201ResponseToJSONTyped(value?: CreateExtension201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'success': value['success'],
        'id': value['id'],
    };
}

